version: "3.8"
services:
  ingester-dk:
    build:
      context: .
      target: dev
    env_file: .env
    networks:
      - elasticsearch
      - ingester
    restart: on-failure
    volumes:
      - ${DC_INGESTER_DK_LIB_REGISTER_COMMON:-.dockerempty}:/home/x/lib/register-common
      - ${DC_INGESTER_DK_LIB_REGISTER_SOURCES_DK:-.dockerempty}:/home/x/lib/register-sources-dk
      - ./.rubocop.yml:/home/x/r/.rubocop.yml
      - ./bin:/home/x/r/bin
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./lib:/home/x/r/lib
      - ./register_ingester_dk.gemspec:/home/x/r/register_ingester_dk.gemspec
      - ./spec:/home/x/r/spec
networks:
  elasticsearch: {}
  ingester: {}
